Aevann1/rDrama

files/routes/settings.py

There is an issue where if a user has a profile picture and they delete it, this url is not unset. A user's profile will show one of the random profile pictures, but the <a> href url is still to the old profile picture, so clicking on the random picture redirects to the old picture.

Nulls highres profile picture url after profile pic is deleted

---

files/classes/submission.py
files/routes/comments.py
files/routes/front.py
files/routes/posts.py

right now sorting by all time comment count times out. thats because for every post backend makes a database call to count comments. 
```
ALTER TABLE submissions add column comment_count integer default 0;
update submissions set comment_count=(select count(id) from comments where parent_submission=submissions.id);
```
also should slightly (unnoticeably) improve front page load times because the same thing happens there (25 database calls to count comments)

cache comment_count in submission

---

files/templates/default.html

Basically when you close a comment, it scrolls up to where that comment started (if not already visible on the page)

Improve comment collapse

---

files/classes/user.py
files/templates/userpage.html

When the ban reason begins with `/comment/...` or `/post/...` then a little link icon is displayed and the reason sends the user to that comment/post.
Works correctly when there's `/comment/...` or `/post/...` and additional words words words.
When no `/comment/...` or `/post/...` is available in the ban reason then there's no hyperlink.

transform post/comment links in ban reason

---

files/templates/default.html

Currently donation link is broken (From ActBlue: "You have attempted to make a contribution to a fundraising page that has no active recipients: either the page's owner has removed all committees or organizations from the page, or we have concluded processing contributions for these committees or organizations.")
Replaced with working link to appropriate charity

Fixed issue with broken donation link

---

files/routes/static.py

adds a redirect to the old /logged_out directory to fix links that were crawled by search engines, or bookmarked/shared by logged out users
example of dead links: https://www.google.com/search?q=site%3Ardrama.net%2Flogged_out

fix dead links because of caching change

---

files/assets/css/main.css
files/templates/header.html
files/templates/journoid_banner.html

The .srd header banner currently has fixed text. However, there have
been many gayops which have made the news. journoid_banner.html is a
dynamic template which selects a random one to present.
Also, stylesheets and markup for the banner have been unslurred.

Add dynamic journoid banner text.

---

files/routes/votes.py
files/templates/comments.html

<pre>Fixes minor UI bug when removing self-upvote on a comment. Previous
behavior, starting from a new comment:
- Initial state: score 1 from self-upvote, upvote button shows
highlighted as `color: var(--primary)`.
- Click on upvote button to remove self-upvote → button
unhighlights, score displays as 0.
- [reload page]
- Score displays as 0, but button is highlighted.
- Click on upvote button → button unhighlights, score displays
as -1. [If you reload the page now, state is score 0 &
highlighted; no change in serverside votes.]
- Click on upvote again → button highlights, score displays as 0.
- [reload page]
- Score displays as 1, button is highlighted.
Direct cause is `templates/comments.html @ L115-117`. I checked
`api_comment`, though, and it adds a vote on new comments, and that …

Fix comment self-upvote removal UI bug.

---

files/routes/static.py
files/templates/badges.html

<pre>Implements feature request to know how many of each badge exists and
to have a 'rarity', a la Steam or PSN badges, relative to number of
non-lurker users.
Because Postgres `COUNT()`s are notoriously costly, /badges has been
memoized for 1hr to avoid a DOS target.</pre>

Add badge quantity and rarity to /badges.

---

files/templates/comments.html

<pre>Turns out the snippet in templates/comments.html was necessary to
get proper behavior in notifications.
Might come back to debug this later, but people use notifications more
than they deal with edge case self-upvotes, so reverting for now.
The changes to prevent coin fuckery with self-upvoting appear to work
correctly in the wild, so leaving those in place.</pre>

Partially revert self-upvote UI bug fix.

---

files/routes/admin.py
files/templates/admin/admin_home.html

<pre>Adds a line in admin_home which displays the currently active git
revision. Current methodology is via manually parsing files in .git.
Consider revising if the application ever has access to `git` shell,
which would obviate some minor security concerns around directory
traversal attacks.</pre>

Add admin status git revision.

---

files/helpers/const.py

<pre>Chose to split text into lines because Python regex supports neither
variable-width nor infinite-width negative lookbehinds. This precludes
a simple pure regex solution. Since all replacements are done at the
word level, this has no obvious ill effects.</pre>

Disable chudtexting in quotes.

---

files/templates/comments.html
files/templates/submission.html
files/templates/submit.html

In line with 542c49dcffe1, repeat a similar fix for the four remaining emoji-btns which had wrong clickboxes.

Fix remaining emoji-btn clickboxes.

---

files/routes/posts.py

<pre>camas is down, replacing it with search.marsey.cat.
Note that when looking for existing Snappy comments to test against,
it appears that something else with Snappy generation is broken.
Ex: /post/66263/-/1876803 puts an entire post URL in the author field.
This commit makes no attempt to fix this. TODO for later.</pre>
<pre>Following up on previous commit:
Issue was that author was being extracted from post.url, not href.
Given that the relevant code section is specifically for /u/s in the
body text of the submission, this was a problem.</pre>

Switch to marsey.cat for Snappy /u/.

---

files/helpers/blackjack.py

<pre>In blackjack, the new double-down and insurance features erroneously
always used coins, even when gambling with mbux.</pre>

Fix blackjack doubledown & insure using wrong currency.

---

files/assets/js/shortcut handler.js

macOS and iOS usually have their shortcut keys using the command key instead of control (e.g. Microsoft Word on Windows binds print to Ctrl+P while the Mac version uses Command+P). Checking KeyboardEvent.metaKey will allow Mac and iOS users to use the command key for the post shortcut which is more comfortable.

Also check KeyboardEvent.metaKey for the post shortcut.

---

files/assets/css/main.css
files/templates/util/assetcache.html

Remove margin-bottom on header tags in blockquotes

---

.gitignore
files/helpers/sanitize.py

While messing with a long string of `>` causing a RecursionLimitExceeded in `mistletoe` (harmless) I discovered that this (or any other) exception in `sanitize` will leave SIGALRM on, causing another exception later, restarting the server or aborting another request. This fixes it.

fix exceptions in sanitize leaving SIGALRM on

---

files/routes/users.py

username redirect cuts 1 character off end of url, For example:
Username: faygo_sucks
Old_username: geese_suck
Behavior:          "https://rdrama.net/@geese_suck" -> "https://rdrama.net/@faygo_suck"
Expected Behavior: "https://rdrama.net/@geese_suck" -> "https://rdrama.net/@faygo_sucks"

Redirect cuts off end of url for username redirect

---

files/templates/userpage.html

there's really no other indication in the UI except the unshadowban button

show if user is shadowbanned for admins

---

files/routes/posts.py

why did we ever catch an exception throw it away, then catch an exception (something get_post already does) and then finally get the post

use get_post to handle getting a post instead of whatever monstrosity was there previously

---

files/assets/js/submit.js
files/helpers/const.py
files/routes/posts.py

we currently spam the /is_repost api on every single character change in the URL box even though there is no way these URLs would ever be submitted to the site
introducing a frankly conservative limit to where we start actually pinging both the api and (on the backend) the database for reposts may help in some cases
the current constant was chosen by taking the length of "http://" and adding 2 to it

don't constantly check for reposts when it's obvious there can't be one
