Aevann1/rDrama

docker-compose.yml, seed-db.sql
signups and notifications and votes and probably more things are broken but its enough to test some stuff locally
=> fix docker-compose.yml, add db-seed 

files/assets/js/all_js.js, files/routes/users.py, files/templates/header.html, files/templates/userpage.html
todo: how to call officially call the transfers, breaking changes? possibly more
done: transfers, registering transfers, rate limits, frontend, notifications, basic error handling
if anyone has any notes about the changes please post here
=> dramacoin transfers

files/classes/comment.py, files/helpers/sanitize.py
see the post by jesus in #report-bugs
=> fix controversial sorting setting for comments

files/routes/static.py, files/templates/patrons.html
by making the code less readable
=> optimize paypigs route

files/routes/admin.py, files/templates/userpage.html
This PR would allow admins to bluecheck verified users and unbluecheck users that turn out not to be who they say they are
=> Admintools/Verification: allow admins to verify users

files/templates/userpage.html
=> Admintools/verification: javasript -> javascript

files/templates/comments.html, files/templates/default.html
It was annoying the fuck out of me to click reply, start typing and the page moving around because of the space
=> When replying to a comment now it autofocus the input

files/templates/default.html
Decreases the jumpiness, still maintaining the basic functionality. Will ask for feedback from the user after it is online.
=> Only 'jumps' if comment above the top. Also decreases offset at the top

files/assets/js/general35.js, files/templates/default.html, files/templates/formatting.html, files/templates/login.html, files/templates/settings.html, files/templates/settings2.html, files/templates/sign_up.html, files/templates/sign_up_failed_ref.html, files/templates/submit.html
Also does not add repeated whitespaces, just the ones needed to separate from the text
=> Can add multiple Marseys in a row

files/templates/emoji_modal.html
When updating to remove jQuery if broke the functionality of adding multiples marseys in a row
=> Fix adding several marseys in place

files/assets/js/general40.js
Just uncommentating the code already preset works in my local deploy of rdrama. I don't know why you commented it, so it may not work in prod (?)
=> Fix tooltip (votes, timestamp) not showing on hover

files/templates/formatting.html
Finished the Allowed Tags table and put the styles in a table but didn't do those. Also, I added tbody to some tables that were missing them, not sure if that was intentional.
=> Formatting - Custom HTML - Allowed Tags

files/classes/submission.py
Hey Avy, Glowiefied user here. I need this simple change in submission json to see if the post am looking at is in draft mode. Don't want to give up my cover for my script
=> add, 'private' json to submission

snappy.txt
=> added months worth of snappy quotes

files/classes/comment.py, files/classes/submission.py, files/classes/user.py, files/routes/settings.py, files/templates/settings_filters.html
Saw #99 and thought that would be quite handy - [video example](https://user-images.githubusercontent.com/90930628/142702535-0b03e094-d3c1-4fc0-bdfa-ba8e4da844ec.mp4)
Requires an additional db column on the `User` model - i.e. `ALTER TABLE users ADD COLUMN teddit BOOLEAN DEFAULT FALSE;`.
=> Allow teddit.net urls in place of reddit.com

files/assets/js/fix-user-popover.js
idk how you want the script loaded so im not touching any of that but this makes it so you can actually view peoples profiles instead of it closing when u try and click the link
=> unfuck the user profile overview thingy

files/helpers/const.py
Its based on this request that Aevann agreed upon
https://rdrama.net/post/28193/i-get-sad-when-carp-doesnt/903756?context=9#context
=> Added Fartbinn and UraniumDonGER to the dong notification

files/templates/CHRISTMAS/modals/ModalGiftCoins.html
probably breaks gifting coins, I haven't tested that lol
=> fix direct messaging on new site

files/assets/css/classic.css
=> make shit look gooder (insanely epic and cool)

snappy_Drama.txt
=> New Snappy update

files/templates/submission.html
=> make seals gooder I think

files/helpers/const.py
=> fixed issue with weird characters in the slur filter

files/routes/front.py, files/templates/home.html
Hi, it's Buck from rdrama.
I made a little feature where anyone can click the CC Mode toggle to only view cc posts. Good for drama ops. Feel free to leave any suggestions and edits since I am new to flask and I use reeeeeeact like a normal human. Thanks
=> Country Club View Mode

files/routes/awards.py, files/templates/shop.html
shows the base price ~~crossed out~~ along with new price for discountcels
sneed
=> Shop discount QoL

files/classes/sub.py, files/classes/user.py, files/templates/userpage.html
=> Show modded subs on userpage

files/routes/users.py
Would help by finding the user that i should remind. Name changes happen
=> added endpoint for getting user data by user_id

files/routes/oauth.py
Oauth was erroring for me because I already had an access_token, so this just makes it return the existing one if it exists. Uses the pattern of catching an integrityerror to avoid race conditions.
=> Fixed oauth error

files/templates/journoid_banner.html
Fix Business Insider URL: was duplicate of LoTT Mashable link.
Add Glenn Beck Program mention.
=> Update journoid banner entries.

files/assets/css/main.css, files/templates/submit.html
=> Fix emojis on freakish browsers & fix buttons

files/templates/submit.html
Now you click the button and not the icon
=> fix emoji button

files/assets/js/emoji_modal.js, files/assets/js/marked.js
This fixes chrome specif bug while keeping firefoxcels fast.
Also regex fix for preview 
---
I hope this clears things up
=> Emoji chrome fix

files/routes/comments.py
<pre>Made the logic of the recent admig upload thread fixes (arguably)
more Pythonic, or at least less verbose.
Also, the banners path was replaced with a duplicate of the sidebars
path during the copypasta. This has been remedied.</pre>
=> Refactor admig logic, fix banners path.

files/helpers/sanitize.py
Like #fortune but to check facts.
=> #factcheck

files/assets/js/comments_v.js
=> Image and emoji quote fixes

files/assets/css/main.css, files/helpers/const.py, files/routes/admin.py, files/templates/util/assetcache.html
* emoji_regex was triggering for :emoji: <em>text</em> :emoji:
* Mirror bug - https://rdrama.net/post/18459/marseycapywalking-megathread-for-bugs-and-suggestions/2021592?context=8#context
* Ban icon bug - https://rdrama.net/post/73033/nsfl-a-dramatard-confesses-his-darkest/2035399?context=8#context
=> Some fixes

files/assets/css/main.css, files/assets/js/emoji_modal.js, files/templates/comments.html, files/templates/submission.html, files/templates/submit.html
Here is an inline emojo picker which lets you start typing an emojo like :mars, which will then be followed by an emoji
https://user-images.githubusercontent.com/104179483/179382483-850a8090-571c-44da-bcb5-9da5facf547b.mp4
The hardcoded limit goes up to 25, but could probably be lower
=> Inline Emojo Picker

files/routes/users.py
Now it fails with appropriate error codes the routes in the profile in JSON mode
Start implementing a .json interface for all logged users reddit-like
PROs:
- easier to debugmaxx applications
- good faith actors can scrap the site more easily :gigachadglow:
CONs:
- bad faith actors can scrap the site more easily :gigachadglow:
- jannitors lose a little of their power of allowlisting applications (they do it for free though)
anyways. I make this commit a separate commit so that Snakes can exclude it from the PR if he doesn't like it (cringe)
=> Errorcodejihad

files/helpers/regex.py
Fixes the UTM regex the previous one wasn't matching the utm things if the subreddit had uppercase letters in it
Repro: https://rdrama.net/h/vidya/post/105312/character-creator-options-in-japanese-games
=> fix utm reeeeeegex

files/routes/oauth.py
fixes an AttributeError if the oauth app doesn't exist
=> return 404 if oauth app doesn't exist

files/routes/awards.py
=> don't leak usernames with deflectors

files/routes/subs.py
i don't know why it says i'm editing that one line at the bottom i just added these lines 🤷🏻‍♀️
=> add mod action if JL3 kicks post from hole

files/routes/static.py
=> add API version of stats page

files/routes/posts.py
also don't try to get submission titles for .gifv, .tif, .tiff
=> only attempt to parse HTML content types for titles

files/helpers/get.py, files/routes/static.py
just remove it
also yeah the branch is wrong lol
=> fix sb thing for get_id

files/helpers/actions.py, files/helpers/const.py, files/helpers/sanitize.py, files/routes/posts.py
introduce a couple of constants, remove duplicate and stripping of text, etc
=> improvements to sanitizations

files/templates/userpage.html, files/templates/userpage_admintools_lower.html
macroify the lower part of the userpage's admin tools
=> lower userpage admin tools as a macro

files/templates/userpage.html, files/templates/userpage_admintools.html
some more refactoring of the userpage
we also change the "remove admin" and "revert admin actions" button to red
=> header admin tools and ban area in userpage_admintools

files/routes/users.py
commit message sux it's not very descriptive
(note: this commit also changes comment sort by id to created_utc, i don't think this is an issue though, in fact it's probably desired behavior)
=> remove duplicate code in upvoters downvoters code

files/helpers/wrappers.py, files/routes/admin.py, files/routes/awards.py, files/routes/casino.py, files/routes/comments.py, files/routes/hats.py, files/routes/posts.py, files/routes/settings.py, files/routes/static.py, files/routes/subs.py, files/routes/users.py
This reverts commit 8700bcc5ee9003efdd6fe739c116842d5786d3e2.
=> Revert "feature required wrapper"

files/helpers/wrappers.py, files/routes/admin.py, files/routes/awards.py, files/routes/casino.py, files/routes/comments.py, files/routes/hats.py, files/routes/posts.py, files/routes/settings.py, files/routes/static.py, files/routes/subs.py, files/routes/users.py
=> Feature required wrapper redux

files/routes/votes.py
=> remove vote code duplication

files/helpers/cloudflare.py, files/helpers/media.py, files/routes/admin.py, files/routes/asset_submissions.py, files/routes/comments.py
need to test first but i think is good
technically this is + code but it's so much better in every way than what we were doing before
=> create cloudflare helper

files/assets/js/award_modal.js, files/assets/js/ban_modal.js, files/assets/js/comments+submission_listing.js, files/assets/js/comments_admin.js, files/assets/js/comments_v.js, files/assets/js/core.js, files/assets/js/delete_post_modal.js, files/assets/js/lottery.js, files/assets/js/report_post_modal.js, files/assets/js/userpage_v.js
=> i hate javascript

files/classes/user.py, files/helpers/actions.py, files/routes/admin.py, files/routes/posts.py, files/routes/reporting.py
doing this as a pr for git related reasons
this fixes a rare error with snappy if no quotes somehow exist and a rare one with invalid data dumped into the ban API
=> fix a couple of potentially rare 500s

files/helpers/get.py
improve get functions in a number of ways
* move functions to get vote and block properties to their own function
* don't query db for block properties if the user is the same as the target or is AUTOJANNY_ID
* add type hints to all of the get functions
* remove weird vestigial load_parent part of get_comment
=> improve get functions

files/helpers/get.py, files/routes/comments.py, files/routes/posts.py
get_comment_v_properties is a new function which adds properties if needed
it's the new replacement for the like 200 lines of duplicated code
=> get: use function to get voted and blocked properties

files/helpers/cron.py, files/helpers/offsitementions.py
this should be more reliable and catch more of these when they're sent
=> all seeing eye: rework reddit notifs a bit

files/helpers/const.py
=> Conjugations of to fuck

files/classes/comment.py, files/classes/submission.py, files/classes/user.py, files/helpers/lazy.py, files/routes/comments.py, files/routes/front.py, files/routes/jinja2.py, files/routes/posts.py, files/routes/votes.py, files/templates/comments.html, files/templates/submission_listing.html
this helps centralize all of the `can_view` functions in the thing and stuff
it makes it easier
=> user can_view functions

files/helpers/roulette.py, files/routes/casino.py, files/templates/casino/roulette_screen.html
let roulettefriends play with 0 and 00
=> [DO NOT MERGE] roulette 0 and 00 bets redux

files/helpers/casino.py, files/routes/casino.py, files/templates/casino/game_screen.html
adds win loss stats to casinos
=> win loss stats to casino games
